### ISSUE TITLE
Add iCloudContainerEnvironment Step Option

### ISSUE THREAD

**Issue by leedsalex** [bitrise-io/steps-xcode-archive#111]
Would it be acceptable to add an `iCloudContainerEnvironment` step option?

Currently, for non app store builds this export options plist key is left out by default (when set to default) in the `hash` method of `bitrise-tools/go-xcode/exportoptions/non_appstore_options.go`. The only workaround is to use the custom export options plist which has become cumbersome because we have many schemes and targets. If a step option were to be introduced it could work in a similar fashion to the other export option overrides such as compile bitcode, or team ID.

If there's no opposition, I'm happy to attempt a PR to add this, although I've never used Go before so I might not get it right the first time around.

**Comment by godrei** [comment]
Hi @leedsalex ,
thanks for the feature request!

Actually, we have a task for this update already, but our idea is not to wire out this option as a new input but set this export option automatically.

If the app uses `CloudKit`, then this key needs to be set with value: `Production` for production ipa exports (ad-hoc, app-store, enterprise) and `Development` for development ipa exports.

What do you think about this idea?

**Comment by leedsalex** [comment]
Thanks for the reply @godrei

That sounds great! It’s what I would have set it to anyway. Do you have an ETA on this update?

**Comment by godrei** [comment]
The task is estimated and ready for sprint, hoverer I do not know if the task will be part of our next week's sprint or not. We will notify you, here.

**Comment by leedsalex** [comment]
Hi @godrei any update on this? Thanks

**Comment by godrei** [comment]
Hi @leedsalex ,
we have released a new version: [2.4.9](https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.4.9) which auto detects the `iCloudContainerEnvironment` export option.

I'll close this issue, but if you need more info/help just let us know and we'll reopen it!

**Comment by leedsalex** [comment]
Thanks @godrei

**Comment by leedsalex** [comment]
@godrei It appears this still doesn't work. Bitrise is reporting in the log that our Entitlements Map for the Target ID is empty. The Xcode step should be retrieving the map from the `archived-expanded-entitlements.xcent` file, but I think this is no longer created post Xcode 9.3 (or so I've read online). Any ideas?

**Comment by viktorbenei** [comment]
@leedsalex can you please copy paste the related build's bitrise.io URL, so that we can check its logs & config?

**Comment by leedsalex** [comment]
@viktorbenei

https://www.bitrise.io/build/c446ff2398373e10

**Comment by trapacska** [comment]
Hey @leedsalex !

Fixing the issue is in progress already. We'll notify you as soon as it is released.

**Comment by trapacska** [comment]
@nab0y4enko thanks for the extra info. It is in-progress actually. We will notify you here.

**Comment by godrei** [comment]
Hi @leedsalex v[2.4.11](https://github.com/bitrise-io/steps-xcode-archive/releases/tag/2.4.11) is released with a new input: `icloud_container_environment`, which you can use to specify the `iCloudContainerEnvironment` export option.
